add_subdirectory(zigpc_common)
add_subdirectory(datastore)
add_subdirectory(zcl_util)
add_subdirectory(zigpc_basic_cluster_mqtt)
add_subdirectory(zigpc_config)
add_subdirectory(zigpc_datastore_fixt)
add_subdirectory(discovery)
add_subdirectory(onboarding)
add_subdirectory(zigpc_network_management_mqtt)
add_subdirectory(zigpc_gateway)
